## Names
Philip lastName, Moiyad Lastname.

## Part 1: .....

## Part 2: Write Python code for data analysis

In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt
np.set_printoptions(precision=3)

hearts = np.loadtxt("./data/heart.csv", delimiter=",")

# hearts

In [2]:
# 2-D Numerical Data Set
twoDNum = np.array([[1, 2, 3, 4, 5, 6],
                    [7, 8, 9, 10, 11, 12],
                    [13, 14, 15, 16, 17, 18],
                    [19, 20, 21, 22, 23, 24],
                    [25, 26, 27, 28, 29, 30],
                    [31, 32, 33, 34, 35, 36],
                    [37, 38, 39, 40, 41, 42],
                    [43, 44, 45, 46, 47, 48],
                    [49, 50, 51, 52, 53, 54]])

In [3]:
twoDNum2 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])

In [4]:
# 2-D Categorical Data Set of Various Types
twoDCat = np.array([['Yes', 'Green', 'Shirt', 'A'],['No', 'Blue', 'Pants', 'B'],['Yes', 'Red', 'Blouse', 'C'],['No', 'Yellow', 'Shirt', 'D']])


In [5]:
# 1-D Vectors
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([1, 2, 3, 4, 5])


#### 2a) (5 points) A function that will compute the mean of a numerical, multidimensional data set input as a 2-dimensional numpy array

In [6]:
# Function for the multivariate mean of a numerical data set
def twoDimMean(inputArr):
    total = np.zeros([len(inputArr[0])])
    num_elements = len(inputArr)

    for i in range(len(inputArr)):
        for j in range(len(inputArr[0])):
            xi = inputArr[:, j]
            total[j] = total[j] + xi[i]

    mean = total/num_elements
    return mean


In [7]:
print("\n2-Dimensional Multivariate Mean:", twoDimMean(twoDNum))
# test : fixed. now correct
# print("mean: ", np.mean(twoDNum, 0))


2-Dimensional Multivariate Mean: [25. 26. 27. 28. 29. 30.]


#### 2b) (5 points) A function that will compute the estimated covariance between two attributes that are input as one-dimensional numpy vectors

In [8]:
# Function for sample covariance between two attributes
def covariance(a, b):
    x, y, total = 0, 0, 0
    n = len(a)
    # attr. Sum 
    for i in range(n):
        x = x + a[i]
        y = y + b[i]
    # attr. Mean
    xMean = x / n
    yMean = y / n

    # Covariance sum
    for i in range(n):
        total = total + ((a[i]) - xMean) * ((b[i]) - yMean)
    covariance = (1 / (n - 1)) * total
    return covariance


In [9]:
print("\nCovariance: ", covariance(vector1, vector2))
# test : correct.
# print("cov: ", np.cov(vector1, vector2)[0][0])


Covariance:  2.5


#### 2c) (5 points) A function that will compute the correlation between two attributes that are input as two numpy vectors.

In [10]:
# Function for correlation between two attributes
def correlation(p1, p2):
    x, y, axb, a2, b2 = 0, 0, 0, 0, 0
    n = len(p1)

    for i in range(n):
        x = x + p1[i]
        y = y + p2[i]

    x_mean = x / n
    y_mean = y / n

    for i in range(n):
        a = (p1[i] - x_mean)
        b = (p2[i] - y_mean)
        axb = axb + (a * b)
        a2 = a2 + (a * a)
        b2 = b2 + (b * b)
    
    correlation = axb / (math.sqrt(a2 * b2))
    
    return correlation


In [11]:
print("\nCorrelation: %f" % correlation(vector1, vector2))

# test : correct.
# print("corr %f" % np.corrcoef(vector1,vector2)[0][0])


Correlation: 1.000000


#### 2d) A function that will normalize the attributes in a two-dimensional numpy array using range normalization.

In [12]:

# Function for min by column
# ref: https://www.geeksforgeeks.org/program-find-minimum-maximum-element-array/
def getMin(inputArr):
    value = inputArr[0]
    n = len(inputArr)
    for i in range(1, n):
        value = min(value, inputArr[i])
    return value


# Function for max by column
# ref: https://www.geeksforgeeks.org/program-find-minimum-maximum-element-array/
def getMax(inputArr):
    value = inputArr[0]
    n = len(inputArr)
    for i in range(1, n):
        value = max(value, inputArr[i])
    return value

def rangeNormal(inputArr):
    rowLen = len(inputArr)
    colLen = len(inputArr[0])
    rngNormal = np.empty([rowLen, colLen])
    
    for row in range(rowLen):
        for col in range(colLen):
            max_min = getMax(inputArr[:, col]) - getMin(inputArr[:, col])
            x_sub_min = (inputArr[row][col] - getMin(inputArr[:, col]))
            rngNormal[row][col] = x_sub_min / max_min
    return rngNormal


In [13]:
print("\nRange Normalized Data:\n", rangeNormal(twoDNum))
print("range normalized 2: ", rangeNormal(twoDNum2))


Range Normalized Data:
 [[0.    0.    0.    0.    0.    0.   ]
 [0.125 0.125 0.125 0.125 0.125 0.125]
 [0.25  0.25  0.25  0.25  0.25  0.25 ]
 [0.375 0.375 0.375 0.375 0.375 0.375]
 [0.5   0.5   0.5   0.5   0.5   0.5  ]
 [0.625 0.625 0.625 0.625 0.625 0.625]
 [0.75  0.75  0.75  0.75  0.75  0.75 ]
 [0.875 0.875 0.875 0.875 0.875 0.875]
 [1.    1.    1.    1.    1.    1.   ]]
range normalized 2:  [[0.    0.    0.   ]
 [0.333 0.333 0.333]
 [0.667 0.667 0.667]
 [1.    1.    1.   ]]


#### 2e) (5 points) A function that will normalize the attributes in a two-dimensional numpy array using standard normalization

In [14]:
# Helper function 
def oneDimMean(inputArr):
    total = 0
    numElements = 0

    for i in range(len(inputArr)):
        total = total + inputArr[i]
        numElements = numElements + 1
    mean = total / numElements
    return mean


# Helper function for SD
def stdDevHelper(inputArr):
    total = 0
    numElements = 0
    mean = oneDimMean(inputArr)

    for i in range(len(inputArr)):
        total = total + (inputArr[i] - mean) ** 2
        numElements = numElements + 1

    std_dev = math.sqrt(total / (numElements - 1))
    return std_dev


def listUnique(inputArr):
    unique = []
    for x in inputArr:
        if x not in unique:
            unique.append(x)
    return unique


def stdNormal(inputArr):
    rowLen = len(inputArr)
    colLen = len(inputArr[0])

    stdNormal = np.empty([rowLen, colLen])
    for i in range(rowLen):
        for j in range(colLen):
            xi = inputArr[i][j]
            colMean = oneDimMean(inputArr[:, j])
            stdDev = stdDevHelper(inputArr[:, j])
            stdNormal[i][j] = (xi - colMean) / stdDev
    return stdNormal

In [15]:
# print("\nStandard Normalized Data:\n", stdNormal(twoDNum))

# test: correct!
# np.set_printoptions(precision=3)
# print(stdNormal(oneHotMatrix))

rangeNormal(np.array([[1, 2, 3, 4], [3, 5, 8, 3]]))

array([[0., 0., 0., 1.],
       [1., 1., 1., 0.]])

#### 2f) (5 points) A function that will compute the covariance matrix of a data set.

In [16]:
def covarMatrix(inputArr):
    # dim = np.array = inputArr.shape
    rowLen = inputArr.shape[1]
    
    covarMatrix = np.empty([rowLen, rowLen])
    for i in range(rowLen):
        for j in range(rowLen):
            xi = inputArr[:, i]
            xj = inputArr[:, j]
            covarMatrix[i,j] = covariance(xi, xj)
    return covarMatrix

# def totalVariance(inputArr):
#     nrow = len(inputArr[0])


In [17]:
# print("\nCovariance Matrix:\n", covarMatrix(twoDNum))
covarHearts = covarMatrix(hearts)
# totalVar = 0
# for i in range(hearts.shape[1]):
#     totalVar += covariance(hearts[:,i], hearts[:,i])

# totalVar

#### 2g) (5 points) A function that will label-encode a two-dimensional categorical data array that is passed in as input.

In [18]:
def labelEncode(inputArr):
    rowLen = len(inputArr)
    colLen = len(inputArr[0])

    lblEncoded = np.empty([rowLen, colLen])
    for i in range(rowLen):
        for j in range(colLen):
            xi = inputArr[:, j]
            xu = listUnique(xi)
            lblEncoded[i][j] = xu.index(xi[i]) + 1

    return lblEncoded


In [19]:
print("\nLabel Encoded Matrix:\n", labelEncode(twoDCat))


Label Encoded Matrix:
 [[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 3. 3. 3.]
 [2. 4. 1. 4.]]


## Part 3

### Convert all categorical attributes using label encoding or one-hot-encoding
a) All categorical variables are already label encoded.
### If your data has missing values, fill in those values with the attribute mean.
b) There are no missing values.

c) mean of the data

In [20]:
print(twoDimMean(hearts))
# hearts.mean(0)
# need to remove non numerical values.

[5.443e+01 6.778e-01 3.174e+00 1.313e+02 2.497e+02 1.481e-01 1.022e+00
 1.497e+02 3.296e-01 1.050e+00 1.585e+00 6.704e-01 4.696e+00 1.444e+00]


In [21]:
print(covarMatrix(hearts))
# need to remove non numerical values.

[[ 8.298e+01 -4.026e-01  8.388e-01  4.443e+01  1.036e+02  4.002e-01
   1.165e+00 -8.487e+01  4.217e-01  2.026e+00  8.942e-01  3.062e+00
   1.876e+00  9.628e-01]
 [-4.026e-01  2.192e-01  1.541e-02 -5.243e-01 -4.880e+00  7.022e-03
   1.834e-02 -8.254e-01  3.969e-02  5.223e-02  1.454e-02  3.837e-02
   3.553e-01  6.939e-02]
 [ 8.388e-01  1.541e-02  9.027e-01 -7.330e-01  4.442e+00 -3.332e-02
   7.047e-02 -6.992e+00  1.580e-01  1.820e-01  7.991e-02  2.026e-01
   4.843e-01  1.974e-01]
 [ 4.443e+01 -5.243e-01 -7.330e-01  3.190e+02  1.597e+02  9.897e-01
   2.070e+00 -1.619e+01  6.964e-01  4.557e+00  1.563e+00  1.445e+00
   4.577e+00  1.382e+00]
 [ 1.036e+02 -4.880e+00  4.442e+00  1.597e+02  2.671e+03  4.633e-01
   8.647e+00 -2.244e+01  1.905e+00  1.640e+00 -1.828e-01  6.174e+00
   2.892e+00  3.037e+00]
 [ 4.002e-01  7.022e-03 -3.332e-02  9.897e-01  4.633e-01  1.267e-01
   1.900e-02  1.855e-01 -6.884e-04 -1.041e-02  9.638e-03  4.158e-02
   3.401e-02 -2.891e-03]
 [ 1.165e+00  1.834e-02  7.047e-02

In [22]:
# scatter plots.

In [23]:

# remove non-nurmerical attributes
rangedNormalized = rangeNormal(hearts)
print(rangedNormalized)



[[0.854 1.    1.    ... 1.    0.    1.   ]
 [0.792 0.    0.667 ... 0.    1.    0.   ]
 [0.583 1.    0.333 ... 0.    1.    1.   ]
 ...
 [0.562 0.    0.333 ... 0.    0.    0.   ]
 [0.583 1.    1.    ... 0.    0.75  0.   ]
 [0.792 1.    1.    ... 1.    0.    1.   ]]


In [24]:
print(stdNormal(hearts))

[[ 1.709  0.688  0.869 ...  2.468 -0.874  1.116]
 [ 1.38  -1.448 -0.183 ... -0.71   1.187 -0.893]
 [ 0.282  0.688 -1.236 ... -0.71   1.187  1.116]
 ...
 [ 0.172 -1.448 -1.236 ... -0.71  -0.874 -0.893]
 [ 0.282  0.688  0.869 ... -0.71   0.672 -0.893]
 [ 1.38   0.688  0.869 ...  2.468 -0.874  1.116]]


In [44]:
correlationList = []
totalRVar = 0
for i in range(hearts.shape[1]):
    for j in range(hearts.shape[1]):
        correlationList.append(correlation(hearts[:,i], hearts[:,j]))
correlationList.sort()
corrSet = set(correlationList)

count = 0
for i in corrSet:
    if(i >= 0.5):
        count += 1
print("Number of correlation pairs larger than 0.5: ", count)

Number of correlation pairs larger than 0.5:  3


In [45]:
totalVar = []
totalRVar = 0
for i in range(hearts.shape[1]):
    for j in range(hearts.shape[1]):
        totalVar.append(covariance(hearts[:,i], hearts[:,j]))
totalVar.sort()
varSet = set(totalVar)
count = 0
for i in varSet:
    if(i < 0):
        count += 1


print("Number of pairs that have negative estimated covariance: ",count)

Number of pairs that have negative estimated covariance:  21


In [46]:
totalVar = 0
for i in range(hearts.shape[1]):
    totalVar += covariance(hearts[:,i], hearts[:,i])
print("Total variance: %.3f" % totalVar)


# totalVarList = []
# totalRVar = 0
# for i in range(hearts.shape[1]):
#     for j in range(hearts.shape[1]):
#         totalVarList.append(covariance(hearts[:,i], hearts[:,j]))
# # totalVarList.sort()
# for i in totalVarList:
#     totalRVar += i

# totalRVar

Total variance: 3619.190


In [49]:
totalRestrictedVar = []
totalRVar = 0
for i in range(hearts.shape[1]):
    for j in range(hearts.shape[1]):
        totalRestrictedVar.append(covariance(hearts[:,i], hearts[:,j]))
totalRestrictedVar.sort()
totalVarRSet = set(totalRestrictedVar)
for i in totalRestrictedVar[-5:]:
    totalRVar += i

# for j in totalVarRSet:
#     totalRVar += j


print("Total variance restricted to the greatest five features estimated: %.3f" % totalRVar)

Total variance restricted to the greatest five features estimated: 3846.617
