## Part 2: Write Python code for data analysis

In [207]:
import numpy as np
import math

In [210]:
# 2-D Numerical Data Set
twoDNum = np.array([[1, 2, 3, 4, 5, 6],
                    [7, 8, 9, 10, 11, 12],
                    [13, 14, 15, 16, 17, 18],
                    [19, 20, 21, 22, 23, 24],
                    [25, 26, 27, 28, 29, 30],
                    [31, 32, 33, 34, 35, 36],
                    [37, 38, 39, 40, 41, 42],
                    [43, 44, 45, 46, 47, 48],
                    [49, 50, 51, 52, 53, 54]])

TypeError: 'tuple' object is not callable

In [211]:
twoDNum2 = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9],
                      [10, 11, 12]])

TypeError: 'tuple' object is not callable

In [212]:
# 2-D Categorical Data Set of Various Types
twoDCat = np.array([['Yes', 'Green', 'Shirt', 'A'],
                    ['No', 'Blue', 'Pants', 'B'],
                    ['Yes', 'Red', 'Blouse', 'C'],
                    ['No', 'Yellow', 'Shirt', 'D']])


TypeError: 'tuple' object is not callable

In [213]:
# 1-D Vectors
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([1, 2, 3, 4, 5])


TypeError: 'tuple' object is not callable

### (5 points) A function that will compute the mean of a numerical, multidimensional data set input as a 2-dimensional numpy array

In [214]:
# Function for the multivariate mean of a numerical data set
def twoDimMean(inputArr):
    total = np.zeros([len(inputArr[0])])
    num_elements = len(inputArr)

    for i in range(len(inputArr)):
        for j in range(len(inputArr[0])):
            xi = inputArr[:, col]
            total[j] = total[j] + x_i[i]

    mean = total
    return mean


In [215]:
print("\n2-Dimensional Multivariate Mean:", twoDimMean(twoDNum))

NameError: name 'twoDNum' is not defined

### (5 points) A function that will compute the estimated covariance between two attributes that are input as one-dimensional numpy vectors

In [216]:
# Function for sample covariance between two attributes
def covariance(a, b):
    x, y, total = 0, 0, 0
    n = len(a)
    # attr. Sum 
    for i in range(n):
        x = x + a[i]
        y = y + b[i]
    # attr. Mean
    xMean = x / n
    yMean = y / n
    # Covariance sum
    for i in range(n):
        total = total + ((a[i]) - xMean) * ((b[i]) - yMean)
    covariance = (1 / (n - 1)) * total
    return covariance


In [217]:
print("\nCovariance: %f" % covariance(vec1, vec2))


Covariance: 2.500000


### (5 points) A function that will compute the correlation between two attributes that are input as two numpy vectors.

In [218]:
# Function for correlation between two attributes
def correlation(p1, p2):
    x, y, axb, a2, b2 = 0, 0, 0, 0, 0
    n = len(p1)

    for i in range(n):
        x = x + p1[i]
        y = y + p2[i]

    x_mean = x / n
    y_mean = y / n

    for i in range(n):
        a = (p1[i] - x_mean)
        b = (p2[i] - y_mean)
        axb = axb + (a * b)
        a2 = a2 + (a * a)
        b2 = b2 + (b * b)
    
    correlation = axb / (math.sqrt(a2 * b2))
    
    return correlation


In [219]:
print("\nCorrelation: %f" % correlation(vec1, vec2))


Correlation: 1.000000


### A function that will normalize the attributes in a two-dimensional numpy array using range normalization.

In [222]:

# Function for min by column
# ref: https://www.geeksforgeeks.org/program-find-minimum-maximum-element-array/
def getMin(input_arr):
    value = input_arr[0]
    n = len(input_arr)
    for i in range(1, n):
        value = min(value, input_arr[i])
    return value


# Function for max by column
# ref: https://www.geeksforgeeks.org/program-find-minimum-maximum-element-array/
def getMax(input_arr):
    value = input_arr[0]
    n = len(input_arr)
    for i in range(1, n):
        value = max(value, input_arr[i])
    return value

def rangeNormal(input_arr):
    rowLen = len(input_arr)
    colLen = len(input_arr[0])
    rngNormal = np.empty([rowLen, colLen])
    
    for row in range(rowLen):
        for col in range(colLen):
            max_min = getMax(input_arr[:, col]) - getMin(input_arr[:, col])
            x_sub_min = (input_arr[row][col] - getMin(input_arr[:, col]))
            rngNormal[row][col] = x_sub_min / max_min
    return rngNormal


In [223]:
print("\nRange Normalized Data:\n", rangeNormal(twoDNum))

NameError: name 'twoDNum' is not defined

### (5 points) A function that will normalize the attributes in a two-dimensional numpy array using standard normalization

In [225]:
# Helper function 
def oneDimMean(input_arr):
    total = 0
    num_elements = 0

    for row in range(len(input_arr)):
        total = total + input_arr[row]
        num_elements = num_elements + 1
    mean = total / num_elements
    return mean


# Helper function for SD
def stdDevHelper(input_arr):
    total = 0
    num_elements = 0
    mean = __1dim_mean__(input_arr)

    for row in range(len(input_arr)):
        total = total + (input_arr[row] - mean) ** 2
        num_elements = num_elements + 1

    std_dev = math.sqrt(total / (num_elements - 1))
    return std_dev


def listUnique(input_arr):
    unique = []
    for x in input_arr:
        if x not in unique:
            unique.append(x)
    return unique


def stdNormal(input_arr):
    rowLen = len(input_arr)
    colLen = len(input_arr[0])

    stdNormal = np.empty([rowLen, colLen])
    for i in range(rowLen):
        for j in range(colLen):
            xi = input_arr[i][j]
            colMean = oneDimMean(input_arr[:, j])
            stdDev = stdDevHelper(input_arr[:, j])
            stdNormal[i][j] = (xi - colMean) / stdDev
    return stdNormal

In [227]:
print("\nStandard Normalized Data:\n", stdNormal(twoDNum))

NameError: name 'twoDNum' is not defined

### (5 points) A function that will compute the covariance matrix of a data set.

In [228]:
def covarMatrix(inputArr):
    dim = np.array = inputArr.shape
    rowLen = dim[1]
    
    covar_matrix = np.empty([rowLen, rowLen])
    for i in range(rowLen):
        for j in range(rowLen):
            x_i = inputArr[:, i]
            x_j = inputArr[:, j]

            covar_matrix[i][j] = covariance(x_i, x_j)
    return covar_matrix

In [229]:
print("\nCovariance Matrix:\n", covarMatrix(twoDNum))

NameError: name 'twoDNum' is not defined

### (5 points) A function that will label-encode a two-dimensional categorical data array that is passed in as input.

In [230]:
def labelEncode(input_arr):
    rowLen = len(input_arr)
    colLen = len(input_arr[0])

    lblEncoded = np.empty([rowLen, colLen])
    for i in range(rowLen):
        for j in range(colLen):
            xi = input_arr[:, j]
            xu = __list_unique__(xi)
            lblEncoded[i][j] = xu.index(xi[i]) + 1

    return lblEncoded


In [231]:
print("\nLabel Encoded Matrix:\n", labelEncode(twoDCat))


Label Encoded Matrix:
 [[1. 1. 1. 1.]
 [2. 2. 2. 1.]
 [2. 2. 3. 2.]
 [3. 3. 1. 3.]]
