## Part 2: Write Python code for data analysis

In [2]:
import numpy as np
import math

In [6]:
# 2-D Numerical Data Set
twoDNum = np.array([[1, 2, 3, 4, 5, 6],
                    [7, 8, 9, 10, 11, 12],
                    [13, 14, 15, 16, 17, 18],
                    [19, 20, 21, 22, 23, 24],
                    [25, 26, 27, 28, 29, 30],
                    [31, 32, 33, 34, 35, 36],
                    [37, 38, 39, 40, 41, 42],
                    [43, 44, 45, 46, 47, 48],
                    [49, 50, 51, 52, 53, 54]])

In [4]:
twoDNum2 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])

In [5]:
# 2-D Categorical Data Set of Various Types
twoDCat = np.array([['Yes', 'Green', 'Shirt', 'A'],['No', 'Blue', 'Pants', 'B'],['Yes', 'Red', 'Blouse', 'C'],['No', 'Yellow', 'Shirt', 'D']])


In [7]:
# 1-D Vectors
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([1, 2, 3, 4, 5])


### (5 points) A function that will compute the mean of a numerical, multidimensional data set input as a 2-dimensional numpy array

In [16]:
# Function for the multivariate mean of a numerical data set
def twoDimMean(inputArr):
    total = np.zeros([len(inputArr[0])])
    num_elements = len(inputArr)

    for i in range(len(inputArr)):
        for j in range(len(inputArr[0])):
            xi = inputArr[:, j]
            total[j] = total[j] + xi[i]

    mean = total
    return mean


In [17]:
print("\n2-Dimensional Multivariate Mean:", twoDimMean(twoDNum))


2-Dimensional Multivariate Mean: [225. 234. 243. 252. 261. 270.]


### (5 points) A function that will compute the estimated covariance between two attributes that are input as one-dimensional numpy vectors

In [38]:
# Function for sample covariance between two attributes
def covariance(a, b):
    x, y, total = 0, 0, 0
    n = len(a)
    # attr. Sum 
    for i in range(n):
        x = x + a[i]
        y = y + b[i]
    # attr. Mean
    xMean = x / n
    yMean = y / n
    # Covariance sum
    for i in range(n):
        total = total + ((a[i]) - xMean) * ((b[i]) - yMean)
    covariance = (1 / (n - 1)) * total
    return covariance


In [40]:
print("\nCovariance: %f" % covariance(vector1, vector2))


Covariance: 2.500000


### (5 points) A function that will compute the correlation between two attributes that are input as two numpy vectors.

In [18]:
# Function for correlation between two attributes
def correlation(p1, p2):
    x, y, axb, a2, b2 = 0, 0, 0, 0, 0
    n = len(p1)

    for i in range(n):
        x = x + p1[i]
        y = y + p2[i]

    x_mean = x / n
    y_mean = y / n

    for i in range(n):
        a = (p1[i] - x_mean)
        b = (p2[i] - y_mean)
        axb = axb + (a * b)
        a2 = a2 + (a * a)
        b2 = b2 + (b * b)
    
    correlation = axb / (math.sqrt(a2 * b2))
    
    return correlation


In [19]:
print("\nCorrelation: %f" % correlation(vector1, vector2))


Correlation: 1.000000


### A function that will normalize the attributes in a two-dimensional numpy array using range normalization.

In [20]:

# Function for min by column
# ref: https://www.geeksforgeeks.org/program-find-minimum-maximum-element-array/
def getMin(input_arr):
    value = input_arr[0]
    n = len(input_arr)
    for i in range(1, n):
        value = min(value, input_arr[i])
    return value


# Function for max by column
# ref: https://www.geeksforgeeks.org/program-find-minimum-maximum-element-array/
def getMax(input_arr):
    value = input_arr[0]
    n = len(input_arr)
    for i in range(1, n):
        value = max(value, input_arr[i])
    return value

def rangeNormal(input_arr):
    rowLen = len(input_arr)
    colLen = len(input_arr[0])
    rngNormal = np.empty([rowLen, colLen])
    
    for row in range(rowLen):
        for col in range(colLen):
            max_min = getMax(input_arr[:, col]) - getMin(input_arr[:, col])
            x_sub_min = (input_arr[row][col] - getMin(input_arr[:, col]))
            rngNormal[row][col] = x_sub_min / max_min
    return rngNormal


In [21]:
print("\nRange Normalized Data:\n", rangeNormal(twoDNum))


Range Normalized Data:
 [[0.    0.    0.    0.    0.    0.   ]
 [0.125 0.125 0.125 0.125 0.125 0.125]
 [0.25  0.25  0.25  0.25  0.25  0.25 ]
 [0.375 0.375 0.375 0.375 0.375 0.375]
 [0.5   0.5   0.5   0.5   0.5   0.5  ]
 [0.625 0.625 0.625 0.625 0.625 0.625]
 [0.75  0.75  0.75  0.75  0.75  0.75 ]
 [0.875 0.875 0.875 0.875 0.875 0.875]
 [1.    1.    1.    1.    1.    1.   ]]


### (5 points) A function that will normalize the attributes in a two-dimensional numpy array using standard normalization

In [41]:
# Helper function 
def oneDimMean(inputArr):
    total = 0
    numElements = 0

    for i in range(len(inputArr)):
        total = total + inputArr[i]
        numElements = numElements + 1
    mean = total / numElements
    return mean


# Helper function for SD
def stdDevHelper(inputArr):
    total = 0
    numElements = 0
    mean = oneDimMean(inputArr)

    for i in range(len(inputArr)):
        total = total + (inputArr[i] - mean) ** 2
        numElements = numElements + 1

    std_dev = math.sqrt(total / (numElements - 1))
    return std_dev


def listUnique(inputArr):
    unique = []
    for x in inputArr:
        if x not in unique:
            unique.append(x)
    return unique


def stdNormal(inputArr):
    rowLen = len(inputArr)
    colLen = len(inputArr[0])

    stdNormal = np.empty([rowLen, colLen])
    for i in range(rowLen):
        for j in range(colLen):
            xi = inputArr[i][j]
            colMean = oneDimMean(inputArr[:, j])
            stdDev = stdDevHelper(inputArr[:, j])
            stdNormal[i][j] = (xi - colMean) / stdDev
    return stdNormal

In [42]:
print("\nStandard Normalized Data:\n", stdNormal(twoDNum))


Standard Normalized Data:
 [[-1.46059349 -1.46059349 -1.46059349 -1.46059349 -1.46059349 -1.46059349]
 [-1.09544512 -1.09544512 -1.09544512 -1.09544512 -1.09544512 -1.09544512]
 [-0.73029674 -0.73029674 -0.73029674 -0.73029674 -0.73029674 -0.73029674]
 [-0.36514837 -0.36514837 -0.36514837 -0.36514837 -0.36514837 -0.36514837]
 [ 0.          0.          0.          0.          0.          0.        ]
 [ 0.36514837  0.36514837  0.36514837  0.36514837  0.36514837  0.36514837]
 [ 0.73029674  0.73029674  0.73029674  0.73029674  0.73029674  0.73029674]
 [ 1.09544512  1.09544512  1.09544512  1.09544512  1.09544512  1.09544512]
 [ 1.46059349  1.46059349  1.46059349  1.46059349  1.46059349  1.46059349]]


### (5 points) A function that will compute the covariance matrix of a data set.

In [43]:
def covarMatrix(inputArr):
    dim = np.array = inputArr.shape
    rowLen = dim[1]
    
    covarMatrix = np.empty([rowLen, rowLen])
    for i in range(rowLen):
        for j in range(rowLen):
            xi = inputArr[:, i]
            xj = inputArr[:, j]

            covarMatrix[i][j] = covariance(xi, xj)
    return covarMatrix

In [44]:
print("\nCovariance Matrix:\n", covarMatrix(twoDNum))


Covariance Matrix:
 [[270. 270. 270. 270. 270. 270.]
 [270. 270. 270. 270. 270. 270.]
 [270. 270. 270. 270. 270. 270.]
 [270. 270. 270. 270. 270. 270.]
 [270. 270. 270. 270. 270. 270.]
 [270. 270. 270. 270. 270. 270.]]


### (5 points) A function that will label-encode a two-dimensional categorical data array that is passed in as input.

In [47]:
def labelEncode(inputArr):
    rowLen = len(inputArr)
    colLen = len(inputArr[0])

    lblEncoded = np.empty([rowLen, colLen])
    for i in range(rowLen):
        for j in range(colLen):
            xi = inputArr[:, j]
            xu = listUnique(xi)
            lblEncoded[i][j] = xu.index(xi[i]) + 1

    return lblEncoded


In [48]:
print("\nLabel Encoded Matrix:\n", labelEncode(twoDCat))


Label Encoded Matrix:
 [[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 3. 3. 3.]
 [2. 4. 1. 4.]]
